/**
 * Nacionalidades para el selector de leads (Fase 3: Recogiendo información).
 * España siempre primera; resto ordenadas alfabéticamente.
 */
export const NATIONALITIES: string[] = [
  "España",
  "Afganistán",
  "Albania",
  "Alemania",
  "Andorra",
  "Angola",
  "Arabia Saudí",
  "Argelia",
  "Argentina",
  "Armenia",
  "Australia",
  "Austria",
  "Azerbaiyán",
  "Bangladesh",
  "Bélgica",
  "Bolivia",
  "Brasil",
  "Bulgaria",
  "Cabo Verde",
  "Canadá",
  "Chile",
  "China",
  "Colombia",
  "Corea del Sur",
  "Costa Rica",
  "Croacia",
  "Cuba",
  "Dinamarca",
  "Ecuador",
  "Egipto",
  "El Salvador",
  "Emiratos Árabes Unidos",
  "Eslovaquia",
  "Eslovenia",
  "Estados Unidos",
  "Estonia",
  "Etiopía",
  "Filipinas",
  "Finlandia",
  "Francia",
  "Georgia",
  "Grecia",
  "Guatemala",
  "Honduras",
  "Hungría",
  "India",
  "Indonesia",
  "Irán",
  "Irak",
  "Irlanda",
  "Israel",
  "Italia",
  "Japón",
  "Jordania",
  "Kazajistán",
  "Kenia",
  "Letonia",
  "Líbano",
  "Libia",
  "Lituania",
  "Luxemburgo",
  "Marruecos",
  "México",
  "Moldavia",
  "Mongolia",
  "Montenegro",
  "Nicaragua",
  "Nigeria",
  "Noruega",
  "Países Bajos",
  "Pakistán",
  "Palestina",
  "Panamá",
  "Paraguay",
  "Perú",
  "Polonia",
  "Portugal",
  "Puerto Rico",
  "Reino Unido",
  "República Checa",
  "República Dominicana",
  "Rumanía",
  "Rusia",
  "Senegal",
  "Serbia",
  "Suecia",
  "Suiza",
  "Sudáfrica",
  "Tailandia",
  "Túnez",
  "Turquía",
  "Ucrania",
  "Uruguay",
  "Venezuela",
  "Vietnam",
  "Otro",
];
